version: '2'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
        restart: always
        ports:
            - 9200:9200
        volumes:
            - ./elasticsearch/data:/usr/share/elasticsearch/data
    logstash:
        build: logstash
        restart: always
        command: logstash -f /config-dir/logstash.conf
        ports:
            - 5044:5044
        links:
            - elasticsearch
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.0.0
        restart: always
        ports:
            - 5601:5601
        links:
            - elasticsearch
    curator:
        build: curator
        restart: always
        links:
            - elasticsearch


